apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sample
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 4
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: python-flask
        image: kanuahs93/flask-sample-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "100m"